# Generated by Django 5.1 on 2026-04-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctors', '0002_doctor_experience_years_alter_doctor_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
    ]
