# Generated by Django 6.0.3 on 2026-07-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_medicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('review', 'Needs Review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
