# Generated by Django 6.0.3 on 2026-04-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospital',
        ),
        migrations.AddField(
            model_name='department',
            name='hospitals',
            field=models.ManyToManyField(related_name='departments', to='hospitals.hospital'),
        ),
    ]
