# Generated by Django 5.1 on 2026-03-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone', models.CharField(max_length=10)),
                ('a_status', models.BooleanField(default=True)),
            ],
        ),
    ]
