# Generated by Django 5.1 on 2026-05-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctoravailability_doctorleave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorleave',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
