# Generated by Django 5.1 on 2026-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_date_doctorleave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleave',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
