# Generated by Django 6.0.3 on 2026-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctorleave_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
