# Generated by Django 6.0.3 on 2026-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reminder_type',
            field=models.CharField(choices=[('general', 'General'), ('12_hours', '12 Hours Before'), ('2_hours', '2 Hours Before')], default='general', max_length=20),
        ),
    ]
