# Generated by Django 6.0.3 on 2026-07-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_reminder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sms_sent',
            new_name='sms_12_sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_2_sent',
            field=models.BooleanField(default=False),
        ),
    ]
